Added upgrade option

diff --git a/iron-pepperflash b/iron-pepperflash
--- a/iron-pepperflash
+++ b/iron-pepperflash
@@ -7,14 +7,23 @@ else
   IRON=iron
 fi
 INSTALLED=$(dpkg -l | grep "^ii  iron" 2> /dev/null)
+if test $1; then
+  if [[ "$1" == "-u" || "$1" == "--upgrade" ]]; then
+    INSTALLED=""
+  else
+    echo "Invalid option.  Usage: $0 [-u|--upgrade]"
+    exit 1
+  fi
+fi
 if [ -z "$INSTALLED" ]; then
   WGET=$(which wget 2> /dev/null)
   if [ $? == 1 ]; then
     sudo apt-get install wget
   fi
-  if [ ! -f $HOME/Downloads/$IRON.deb ]; then
-    wget http://www.srware.net/downloads/$IRON.deb
+  if [ -f $HOME/Downloads/$IRON.deb ]; then
+    rm -f $HOME/Downloads/$IRON.deb
   fi
+  wget http://www.srware.net/downloads/$IRON.deb
   if [ ! -f $HOME/Downloads/$IRON.deb ]; then
     echo "Unable to locate $IRON.deb.  Install failed."
     exit 1
@@ -32,9 +41,14 @@ if [ -z "$VER" ]; then
   echo "Unable to determine the Pepperflash version.  Install failed."
   exit 1
 fi
+INSTALLED=$(dpkg -l | grep "^ii  iron" 2> /dev/null)
+if [ -z "$INSTALLED" ]; then
+  echo "SRWare Iron with Pepperflash not installed."
+  exit 1
+fi
 PEPPERFLASH=$(grep pepperflash /usr/share/applications/iron.desktop 2> /dev/null)
 if [ ! -z "$PEPPERFLASH" ]; then
-  echo "SRWare Iron with Pepperflash already configured."
+  echo "SRWare Iron with Pepperflash already installed."
 else
   sudo sed -i "s|/usr/share/iron/iron|/usr/share/iron/iron --ppapi-flash-path=/usr/lib/pepperflashplugin-nonfree/libpepflashplayer.so --ppapi-flash-version=$VER|" /usr/share/applications/iron.desktop
   echo "SRWare Iron with Pepperflash installed successfully."
